default: &default
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: meal_support_app_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: meal_support_app_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode 
  url: <%= ENV['DATABASE_URL'] %>